version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app # Link everything else
      # NOTE following command is commented out because it is throwing a permission denied error
      # - /var/app/node_modules # Dont link node_modules 

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/app
    command: [ "npm", "run", "test" ]
